In [9]:
## Assignment 06 Data cleaning Assignment

## Ans 1

import numpy as np



def powerraiser(list1,k,increasing):
    MatrixOut=np.array([])
    if increasing==True:
        MatrixOut=np.array([x**i for x in list1 for i in range(k)]).reshape(list1.size,k)
        return MatrixOut
    if increasing==False:
        MatrixOut=np.array([x**(k-i-1) for x in list1 for i in range(k)]).reshape(list1.size,k)
        return MatrixOut
    
##Test 1
InputList=np.array([1,2,3,4,5])
g=3
IncCounter=True
    
            
print("the output array is:"+str(powerraiser(InputList,g,IncCounter)))

##Test 1
InputList1=np.array([1,4,7,6,9,5])
g1=len(InputList)
IncCounter1=False
    
            
print("the output array is:"+str(powerraiser(InputList1,g1,IncCounter1)))

the output array is:[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
the output array is:[[   1    1    1    1    1]
 [ 256   64   16    4    1]
 [2401  343   49    7    1]
 [1296  216   36    6    1]
 [6561  729   81    9    1]
 [ 625  125   25    5    1]]


In [10]:
##Ans 2

import pandas as pd
import numpy as np

listK=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
Win=3


def rolAvg(list1,Window):
    Avg=0
    ListAvg=np.array([])
    for i in range(0,(len(list1)-Window+1)):
        Avg=((list1[i]+list1[i+1]+list1[i+2])/Window)
        ListAvg=np.append(ListAvg,Avg)
    return ListAvg
    
##Test

print("Rolling average is:"+str(rolAvg(listK,Win)))

Rolling average is:[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
